if (EMSCRIPTEN)
    add_library(SDL2 INTERFACE)
    target_compile_options(SDL2 INTERFACE -sUSE_SDL=2 -sALLOW_MEMORY_GROWTH=1 -fno-exceptions)
    target_link_options(SDL2 INTERFACE -sUSE_SDL=2 -sALLOW_MEMORY_GROWTH=1 -fno-exceptions)
    add_library(SDL2::SDL2 ALIAS SDL2)
else()
    find_package(SDL2 REQUIRED)
    if (NOT TARGET SDL2::SDL2)
        add_library(SDL2 INTERFACE)
        target_include_directories(SDL2 INTERFACE "${SDL_INCLUDE_DIRS}")
        target_link_libraries(SDL2 INTERFACE "${SDL2_LIBRARIES}")
        add_library(SDL2::SDL2 ALIAS SDL2)
    endif()
endif()
